# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: maria_db
    image: mariadb:10.10.5-jammy
    restart: always
    ports:
      - 3306:3306

    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
